
#################################################
### THIS FILE WAS AUTOGENERATED! DO NOT EDIT! ###
#################################################
# file to edit: dev_nb/02_Fully-Connected.ipynb

from exp.nb_01 import *


def get_data():
    """Download MNIST dataset and return training and validation tensors."""
    path = datasets.download_data(MNIST_URL, ext=".gz")

    with gzip.open(path, "rb") as f:
        ((x_train, y_train), (x_valid, y_valid), _) = pickle.load(f, encoding="latin-1")

    return map(tensor, (x_train, y_train, x_valid, y_valid))


def normalize(x, mean, std):
    """Normalize x by first centering it and then scale it."""
    return (x - mean) / std

def test_near_zero(a, tol=1e-3):
    assert a.abs() < tol, f"Near zero: {a}"

from torch.nn import init

def mse(output, targ):
    """Compute Mean Squared Error."""
    return (output.squeeze(-1) - targ).pow(2).mean()

from torch import nn